{
  "pets" [
    {"name": "Bella", "type": "Dog", "breed": "Labrador Retriever", "weight": "30kg", "color": "Black"},
    {"name": "Max", "type": "Dog", "breed": "German Shepherd", "weight": "35kg", "color": "Brown"},
    {"name": "Charlie", "type": "Dog", "breed": "Bulldog", "weight": "25kg", "color": "White"},
    {"name": "Luna", "type": "Cat", "breed": "Siamese", "weight": "5kg", "color": "Grey"},
    {"name": "Lucy", "type": "Cat", "breed": "Persian", "weight": "6kg", "color": "White"},
    {"name": "Cooper", "type": "Dog", "breed": "Golden Retriever", "weight": "32kg", "color": "Golden"},
    {"name": "Rocky", "type": "Dog", "breed": "Boxer", "weight": "29kg", "color": "Brindle"},
    {"name": "Molly", "type": "Cat", "breed": "Maine Coon", "weight": "8kg", "color": "Brown"},
    {"name": "Daisy", "type": "Cat", "breed": "Bengal", "weight": "7kg", "color": "Spotted"},
    {"name": "Sadie", "type": "Dog", "breed": "Poodle", "weight": "20kg", "color": "Black"},
    {"name": "Toby", "type": "Dog", "breed": "Beagle", "weight": "18kg", "color": "Tri-color"},
    {"name": "Bailey", "type": "Dog", "breed": "Dachshund", "weight": "9kg", "color": "Brown"},
    {"name": "Oliver", "type": "Cat", "breed": "Ragdoll", "weight": "6kg", "color": "White"},
    {"name": "Zoe", "type": "Cat", "breed": "Russian Blue", "weight": "4kg", "color": "Blue-grey"},
    {"name": "Buddy", "type": "Dog", "breed": "Border Collie", "weight": "23kg", "color": "Black and White"},
    {"name": "Lola", "type": "Cat", "breed": "Sphynx", "weight": "4kg", "color": "Pink"},
    {"name": "Jake", "type": "Dog", "breed": "Cocker Spaniel", "weight": "15kg", "color": "Golden"},
    {"name": "Sophie", "type": "Cat", "breed": "British Shorthair", "weight": "5kg", "color": "Grey"},
    {"name": "Jack", "type": "Dog", "breed": "Australian Shepherd", "weight": "25kg", "color": "Merle"},
    {"name": "Nala", "type": "Cat", "breed": "Savannah", "weight": "7kg", "color": "Spotted"},
    {"name": "Riley", "type": "Dog", "breed": "Shih Tzu", "weight": "7kg", "color": "White and Brown"},
    {"name": "Milo", "type": "Cat", "breed": "Abyssinian", "weight": "4kg", "color": "Ruddy"},
    {"name": "Chloe", "type": "Dog", "breed": "Yorkshire Terrier", "weight": "3kg", "color": "Black and Tan"},
    {"name": "Harley", "type": "Cat", "breed": "Scottish Fold", "weight": "5kg", "color": "Grey"},
    {"name": "Buster", "type": "Dog", "breed": "Chihuahua", "weight": "2kg", "color": "Fawn"},
    {"name": "Sasha", "type": "Cat", "breed": "American Shorthair", "weight": "4kg", "color": "Brown Tabby"},
    {"name": "Duke", "type": "Dog", "breed": "Rottweiler", "weight": "50kg", "color": "Black and Tan"},
    {"name": "Maggie", "type": "Cat", "breed": "Turkish Angora", "weight": "5kg", "color": "White"},
    {"name": "Leo", "type": "Dog", "breed": "Bernese Mountain Dog", "weight": "40kg", "color": "Tricolor"},
    {"name": "Misty", "type": "Cat", "breed": "Birman", "weight": "5kg", "color": "Seal Point"},
    {"name": "Ginger", "type": "Dog", "breed": "Cavalier King Charles Spaniel", "weight": "6kg", "color": "Blenheim"},
    {"name": "Oscar", "type": "Cat", "breed": "Egyptian Mau", "weight": "5kg", "color": "Silver Spotted"},
    {"name": "Ruby", "type": "Dog", "breed": "Brittany", "weight": "15kg", "color": "Orange and White"},
    {"name": "Simba", "type": "Cat", "breed": "Oriental Shorthair", "weight": "4kg", "color": "Chocolate"},
    {"name": "Zeus", "type": "Dog", "breed": "Great Dane", "weight": "70kg", "color": "Harlequin"},
    {"name": "Jasper", "type": "Cat", "breed": "Japanese Bobtail", "weight": "4kg", "color": "Calico"},
    {"name": "Bentley", "type": "Dog", "breed": "English Mastiff", "weight": "80kg", "color": "Fawn"},
    {"name": "Shadow", "type": "Cat", "breed": "Norwegian Forest", "weight": "6kg", "color": "Black"},
    {"name": "Bentley", "type": "Dog", "breed": "French Bulldog", "weight": "12kg", "color": "Brindle"},
    {"name": "Coco", "type": "Cat", "breed": "Himalayan", "weight": "5kg", "color": "Seal Point"},
    {"name": "Zara", "type": "Dog", "breed": "Samoyed", "weight": "23kg", "color": "White"},
    {"name": "Loki", "type": "Cat", "breed": "Burmese", "weight": "5kg", "color": "Sable"},
    {"name": "Kobe", "type": "Dog", "breed": "Doberman", "weight": "40kg", "color": "Black and Rust"},
    {"name": "Hazel", "type": "Cat", "breed": "Turkish Van", "weight": "5kg", "color": "Van Pattern"},
    {"name": "Rocco", "type": "Dog", "breed": "Pit Bull", "weight": "30kg", "color": "Blue"},
    {"name": "Lulu", "type": "Cat", "breed": "Balinese", "weight": "4kg", "color": "Chocolate Point"},
    {"name": "Gizmo", "type": "Dog", "breed": "Papillon", "weight": "4kg", "color": "White and Sable"},
    {"name": "Kiki", "type": "Cat", "breed": "Manx", "weight": "5kg", "color": "Black"},
    {"name": "Rex", "type": "Dog", "breed": "Alaskan Malamute", "weight": "45kg", "color": "Gray and White"},
    {"name": "Snowball", "type": "Cat", "breed": "Turkish Angora", "weight": "5kg", "color": "White"},
    {"name": "Ollie", "type": "Dog", "breed": "Basset Hound", "weight": "25kg", "color": "Tri-color"},
    {"name": "Angel", "type": "Cat", "breed": "Somali", "weight": "4kg", "color": "Ruddy"},
    {"name": "Hunter", "type": "Dog", "breed": "Rhodesian Ridgeback", "weight": "36kg", "color": "Wheaten"},
    {"name": "Belle", "type": "Cat", "breed": "Snowshoe", "weight": "4kg", "color": "Seal Point"},
    {"name": "Rusty", "type": "Dog", "breed": "Irish Setter", "weight": "32kg", "color": "Red"},
    {"name": "Bella", "type": "Dog", "breed": "Labrador Retriever", "weight": "30kg", "color": "Black"},
    {"name": "Max", "type": "Dog", "breed": "German Shepherd", "weight": "35kg", "color": "Brown"},
    {"name": "Charlie", "type": "Dog", "breed": "Bulldog", "weight": "25kg", "color": "White"},
    {"name": "Luna", "type": "Cat", "breed": "Siamese", "weight": "5kg", "color": "Grey"},
    {"name": "Lucy", "type": "Cat", "breed": "Persian", "weight": "6kg", "color": "White"},
    {"name": "Cooper", "type": "Dog", "breed": "Golden Retriever", "weight": "32kg", "color": "Golden"},
    {"name": "Rocky", "type": "Dog", "breed": "Boxer", "weight": "29kg", "color": "Brindle"},
    {"name": "Molly", "type": "Cat", "breed": "Maine Coon", "weight": "8kg", "color": "Brown"},
    {"name": "Daisy", "type": "Cat", "breed": "Bengal", "weight": "7kg", "color": "Spotted"},
    {"name": "Sadie", "type": "Dog", "breed": "Poodle", "weight": "20kg", "color": "Black"},
    {"name": "Toby", "type": "Dog", "breed": "Beagle", "weight": "18kg", "color": "Tri-color"},
    {"name": "Bailey", "type": "Dog", "breed": "Dachshund", "weight": "9kg", "color": "Brown"},
    {"name": "Oliver", "type": "Cat", "breed": "Ragdoll", "weight": "6kg", "color": "White"},
    {"name": "Zoe", "type": "Cat", "breed": "Russian Blue", "weight": "4kg", "color": "Blue-grey"},
    {"name": "Buddy", "type": "Dog", "breed": "Border Collie", "weight": "23kg", "color": "Black and White"},
    {"name": "Lola", "type": "Cat", "breed": "Sphynx", "weight": "4kg", "color": "Pink"},
    {"name": "Jake", "type": "Dog", "breed": "Cocker Spaniel", "weight": "15kg", "color": "Golden"},
    {"name": "Sophie", "type": "Cat", "breed": "British Shorthair", "weight": "5kg", "color": "Grey"},
    {"name": "Jack", "type": "Dog", "breed": "Australian Shepherd", "weight": "25kg", "color": "Merle"},
    {"name": "Nala", "type": "Cat", "breed": "Savannah", "weight": "7kg", "color": "Spotted"},
    {"name": "Riley", "type": "Dog", "breed": "Shih Tzu", "weight": "7kg", "color": "White and Brown"},
    {"name": "Milo", "type": "Cat", "breed": "Abyssinian", "weight": "4kg", "color": "Ruddy"},
    {"name": "Chloe", "type": "Dog", "breed": "Yorkshire Terrier", "weight": "3kg", "color": "Black and Tan"},
    {"name": "Harley", "type": "Cat", "breed": "Scottish Fold", "weight": "5kg", "color": "Grey"},
    {"name": "Buster", "type": "Dog", "breed": "Chihuahua", "weight": "2kg", "color": "Fawn"},
    {"name": "Sasha", "type": "Cat", "breed": "American Shorthair", "weight": "4kg", "color": "Brown Tabby"},
    {"name": "Duke", "type": "Dog", "breed": "Rottweiler", "weight": "50kg", "color": "Black and Tan"},
    {"name": "Maggie", "type": "Cat", "breed": "Turkish Angora", "weight": "5kg", "color": "White"},
    {"name": "Leo", "type": "Dog", "breed": "Bernese Mountain Dog", "weight": "40kg", "color": "Tricolor"},
    {"name": "Misty", "type": "Cat", "breed": "Birman", "weight": "5kg", "color": "Seal Point"},
    {"name": "Ginger", "type": "Dog", "breed": "Cavalier King Charles Spaniel", "weight": "6kg", "color": "Blenheim"},
    {"name": "Oscar", "type": "Cat", "breed": "Egyptian Mau", "weight": "5kg", "color": "Silver Spotted"},
    {"name": "Ruby", "type": "Dog", "breed": "Brittany", "weight": "15kg", "color": "Orange and White"},
    {"name": "Simba", "type": "Cat", "breed": "Oriental Shorthair", "weight": "4kg", "color": "Chocolate"},
    {"name": "Zeus", "type": "Dog", "breed": "Great Dane", "weight": "70kg", "color": "Harlequin"},
    {"name": "Jasper", "type": "Cat", "breed": "Japanese Bobtail", "weight": "4kg", "color": "Calico"},
    {"name": "Bentley", "type": "Dog", "breed": "English Mastiff", "weight": "80kg", "color": "Fawn"},
    {"name": "Shadow", "type": "Cat", "breed": "Norwegian Forest", "weight": "6kg", "color": "Black"},
    {"name": "Bentley", "type": "Dog", "breed": "French Bulldog", "weight": "12kg", "color": "Brindle"},
    {"name": "Coco", "type": "Cat", "breed": "Himalayan", "weight": "5kg", "color": "Seal Point"},
    {"name": "Zara", "type": "Dog", "breed": "Samoyed", "weight": "23kg", "color": "White"},
    {"name": "Loki", "type": "Cat", "breed": "Burmese", "weight": "5kg", "color": "Sable"},
    {"name": "Kobe", "type": "Dog", "breed": "Doberman", "weight": "40kg", "color": "Black and Rust"},
    {"name": "Hazel", "type": "Cat", "breed": "Turkish Van", "weight": "5kg", "color": "Van Pattern"},
    {"name": "Rocco", "type": "Dog", "breed": "Pit Bull", "weight": "30kg", "color": "Blue"},
    {"name": "Lulu", "type": "Cat", "breed": "Balinese", "weight": "4kg", "color": "Chocolate Point"},
    {"name": "Gizmo", "type": "Dog", "breed": "Papillon", "weight": "4kg", "color": "White and Sable"},
    {"name": "Kiki", "type": "Cat", "breed": "Manx", "weight": "5kg", "color": "Black"},
    {"name": "Rex", "type": "Dog", "breed": "Alaskan Malamute", "weight": "45kg", "color": "Gray and White"},
    {"name": "Snowball", "type": "Cat", "breed": "Turkish Angora", "weight": "5kg", "color": "White"},
    {"name": "Ollie", "type": "Dog", "breed": "Basset Hound", "weight": "25kg", "color": "Tri-color"},
    {"name": "Angel", "type": "Cat", "breed": "Somali", "weight": "4kg", "color": "Ruddy"},
    {"name": "Hunter", "type": "Dog", "breed": "Rhodesian Ridgeback", "weight": "36kg", "color": "Wheaten"},
    {"name": "Belle", "type": "Cat", "breed": "Snowshoe", "weight": "4kg", "color": "Seal Point"},
    {"name": "Rusty", "type": "Dog", "breed": "Irish Setter", "weight": "32kg", "color": "Red"},
    {"name": "Tigger", "type": "Cat", "breed": "Ocicat", "weight": "5kg", "color": "Spotted"}
]
}